# Generated by Django 4.2.7 on 2023-12-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='emael',
        ),
    ]
